### ISSUE TITLE
Symfony update of Request class requiring a second argument for setTrustedProxies

### ISSUE THREAD

**Issue by EdwinDayot** [vluzrmos/lumen-cors#10]
Hi,

After an update of all my dependencies (running Lumen 5.4), I noticed the following error:

`The Symfony\\Component\\HttpFoundation\\Request::setTrustedProxies() method expects a bit field of Request::HEADER_* as second argument. Defining it is required since version 3.3. See http://symfony.com/doc/current/components/http_foundation/trusting_proxies.html for more info.`

Documentation in the file Request shows for argument `trustedHeaderSet` of `setTrustedProxies`method: 
```php
/**
 * @param int   $trustedHeaderSet A bit field of Request::HEADER_*, usually either Request::HEADER_FORWARDED or Request::HEADER_X_FORWARDED_ALL, to set which headers to trust from your proxies
 */
```

It seems that the line:
``` php
$request->setTrustedProxies($request->getClientIps());
```

Should also implement the following:
``` php
$request->setTrustedProxies($request->getClientIps(), Request::HEADER_X_FORWARDED_ALL);
```

Or something like this :)

Thanks !

**Comment by vluzrmos** [comment]
Trying to fix it....
