### ISSUE TITLE
Dependency conflict with lumen V6

### ISSUE THREAD

**Issue by MaherSaleem** [vluzrmos/lumen-cors#11]
This package has a conflict with illuminate/support, while trying to upgrade to lumen v6. Please 

Please check the following error log.

``
 **Problem 1**
    - illuminate/http 5.4.x-dev requires illuminate/session 5.4.* -> satisfiable by illuminate/session[5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - illuminate/http v5.4.0 requires illuminate/session 5.4.* -> satisfiable by illuminate/session[5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - illuminate/http v5.4.13 requires illuminate/session 5.4.* -> satisfiable by illuminate/session[5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - illuminate/http v5.4.17 requires illuminate/session 5.4.* -> satisfiable by 

 **Conclusion: don't install laravel/framework v6.0.2|install vluzrmos/lumen-cors v2.1.2
    - Installation request for vluzrmos/lumen-cors 2.1.* -> satisfiable by vluzrmos/lumen-cors[2.1.x-dev, v2.1.0, v2.1.1, v2.1.2].**
``

**Comment by luistimana** [comment]
x2

**Comment by vluzrmos** [comment]
Please consider to use [fruitcake/laravel-cors](https://github.com/fruitcake/laravel-cors#lumen). That is more flexible and is part of the Laravel skeleton app.
