### ISSUE TITLE
Problems with custom routes

### ISSUE THREAD

**Issue by jaswdr** [vluzrmos/lumen-cors#2]
When use custom routes like "$app->get('/user/{id}')" the server respond with code 405, like the route don't exist.
I've look and probably is something with this line in CorsServiceProvider class:

$this->app->options($request->path(), function(){
    return new Response('OK', 200);
});

I think that Laravel is considering the fixed route /user/3 instead of /user/{id} and the GET method

**Comment by vluzrmos** [comment]
Thanks, I'll check it out!

**Comment by vluzrmos** [comment]
Done!

Update your lumen-cors to v1.0.5

**Comment by vluzrmos** [comment]
Update your lumen-cors to v1.0.4

**Comment by jaswdr** [comment]
Thanks for that, I'll checkout
